### ISSUE TITLE
DATA_FILES_PATH non completo

### ISSUE THREAD

**Issue by rglauco** [Sielte/rao-pubblico#3]
Nel file [settings.py](https://github.com/Sielte/rao-pubblico/blob/master/rao/rao/settings.py), la variabile: `DATA_FILES_PATH = os.environ.get('DATA_FILES_PATH', 'data/')` causa il mancato caricamento dei csv nel db al cambio pwd.

```
[v. 1.0.1] [13/Oct/20 16:54:58] ERROR [init_nation] [agency.utils.utils_setup:51] tb = ['Traceback (most recent call last):\n', '  File "/rao/agency/utils/utils_setup.py", line 34, in init_nation\n    with open(os.path.join(settings.DATA_FILES_PATH, file), encoding=\'utf-8\') as csv_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'data/nazioni.csv'\n"]
[v. 1.0.1] [13/Oct/20 16:54:58] ERROR [init_prefix] [agency.utils.utils_setup:156] Exception: [Errno 2] No such file or directory: 'data/prefissi.csv'
[v. 1.0.1] [13/Oct/20 16:54:58] ERROR [init_prefix] [agency.utils.utils_setup:157] exception_value = [Errno 2] No such file or directory: 'data/prefissi.csv', value = <class 'type'>
[v. 1.0.1] [13/Oct/20 16:54:58] ERROR [init_prefix] [agency.utils.utils_setup:158] tb = ['Traceback (most recent call last):\n', '  File "/rao/agency/utils/utils_setup.py", line 143, in init_prefix\n    with open(os.path.join(settings.DATA_FILES_PATH, file), encoding=\'utf-8\') as csv_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'data/prefissi.csv'\n"]
[v. 1.0.1] [13/Oct/20 16:54:58] ERROR [init_county] [agency.utils.utils_setup:83] Exception: [Errno 2] No such file or directory: 'data/province.csv'
[v. 1.0.1] [13/Oct/20 16:54:58] ERROR [init_county] [agency.utils.utils_setup:84] exception_value = [Errno 2] No such file or directory: 'data/province.csv', value = <class 'type'>
[v. 1.0.1] [13/Oct/20 16:54:58] ERROR [init_county] [agency.utils.utils_setup:85] tb = ['Traceback (most recent call last):\n', '  File "/rao/agency/utils/utils_setup.py", line 71, in init_county\n    with open(os.path.join(settings.DATA_FILES_PATH, file), encoding=\'utf-8\') as csv_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'data/province.csv'\n"]
[v. 1.0.1] [13/Oct/20 16:54:58] ERROR [init_municipality] [agency.utils.utils_setup:128] Exception: [Errno 2] No such file or directory: 'data/ANPR_archivio_comuni.csv'
[v. 1.0.1] [13/Oct/20 16:54:58] ERROR [init_municipality] [agency.utils.utils_setup:129] exception_value = [Errno 2] No such file or directory: 'data/ANPR_archivio_comuni.csv', value = <class 'type'>
[v. 1.0.1] [13/Oct/20 16:54:58] ERROR [init_municipality] [agency.utils.utils_setup:130] tb = ['Traceback (most recent call last):\n', '  File "/rao/agency/utils/utils_setup.py", line 97, in init_municipality\n    with open(os.path.join(settings.DATA_FILES_PATH, file), encoding=\'utf-8\') as csv_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'data/ANPR_archivio_comuni.csv'\n"]
```

Provando a settarla in questo modo `DATA_FILES_PATH=os.path.join(BASE_DIR, 'data/')`  il caricamento dei csv riesce.

**Comment by fgugliuzza** [comment]
Non è necessario avere la variabile definita nell'ENV, in quanto se non è presente viene considerato il path relativo `'data/'`. È quindi sufficiente creare la directory `data` nel path in cui risiede l'applicazione.

**Comment by rglauco** [comment]
La ringrazio per la risposta, credo sia opportuno precisare il contesto: siamo nell'istanza docker appena creata, con db sqlite istanziato. La procedura di creazione dell'amministratore e' al momento del cambio pwd.

La dir `/rao/data` esiste gia', e contiene i files csv; stando a quanto leggo nei sorgenti non credo si debba creare ex novo altrove.

Il problema sembra risiedere proprio nel path relativo, che l'applicazione non trova, mentre con il path assoluto confermo che il caricamento avviene correttamente.

Con l'ultima versione dei sorgenti, all'evento del cambio pwd questo e' il log:
```
Message: 'RMPGLC74H07L483V - Link verificato.'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/rao/agency/utils/utils_setup.py", line 35, in init_nation
    with open(os.path.join(settings.DATA_FILES_PATH, file), encoding='utf-8') as csv_file:
FileNotFoundError: [Errno 2] No such file or directory: 'data/nazioni.csv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/logging/__init__.py", line 994, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 580, in format
    s = self.formatMessage(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 549, in formatMessage
    return self._style.format(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 391, in format
    return self._fmt % record.__dict__
KeyError: 'rao_name'
Call stack:
  File "/usr/local/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/rao/agency/utils/utils.py", line 509, in do_import
    init_nation(None)
  File "/rao/agency/utils/utils_setup.py", line 50, in init_nation
    LOG.error("Exception: {}".format(str(e)), extra=set_client_ip(request))
Message: "Exception: [Errno 2] No such file or directory: 'data/nazioni.csv'"
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/rao/agency/utils/utils_setup.py", line 35, in init_nation
    with open(os.path.join(settings.DATA_FILES_PATH, file), encoding='utf-8') as csv_file:
FileNotFoundError: [Errno 2] No such file or directory: 'data/nazioni.csv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/logging/__init__.py", line 994, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 580, in format
    s = self.formatMessage(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 549, in formatMessage
    return self._style.format(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 391, in format
    return self._fmt % record.__dict__
KeyError: 'rao_name'
Call stack:
  File "/usr/local/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/rao/agency/utils/utils.py", line 509, in do_import
    init_nation(None)
  File "/rao/agency/utils/utils_setup.py", line 51, in init_nation
    LOG.error('exception_value = %s, value = %s' % (value, type,), extra=set_client_ip(request))
Message: "exception_value = [Errno 2] No such file or directory: 'data/nazioni.csv', value = <class 'type'>"
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/rao/agency/utils/utils_setup.py", line 35, in init_nation
    with open(os.path.join(settings.DATA_FILES_PATH, file), encoding='utf-8') as csv_file:
FileNotFoundError: [Errno 2] No such file or directory: 'data/nazioni.csv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/logging/__init__.py", line 994, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 580, in format
    s = self.formatMessage(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 549, in formatMessage
    return self._style.format(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 391, in format
    return self._fmt % record.__dict__
KeyError: 'rao_name'
Call stack:
  File "/usr/local/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/rao/agency/utils/utils.py", line 509, in do_import
    init_nation(None)
  File "/rao/agency/utils/utils_setup.py", line 52, in init_nation
    LOG.error('tb = %s' % traceback.format_exception(type, value, tb), extra=set_client_ip(request))
Message: 'tb = [\'Traceback (most recent call last):\\n\', \'  File "/rao/agency/utils/utils_setup.py", line 35, in init_nation\\n    with open(os.path.join(settings.DATA_FILES_PATH, file), encoding=\\\'utf-8\\\') as csv_file:\\n\', "FileNotFoundError: [Errno 2] No such file or directory: \'data/nazioni.csv\'\\n"]'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/rao/agency/utils/utils_setup.py", line 144, in init_prefix
    with open(os.path.join(settings.DATA_FILES_PATH, file), encoding='utf-8') as csv_file:
FileNotFoundError: [Errno 2] No such file or directory: 'data/prefissi.csv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/logging/__init__.py", line 994, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 580, in format
    s = self.formatMessage(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 549, in formatMessage
    return self._style.format(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 391, in format
    return self._fmt % record.__dict__
KeyError: 'rao_name'
Call stack:
  File "/usr/local/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/rao/agency/utils/utils.py", line 512, in do_import
    init_prefix(None)
  File "/rao/agency/utils/utils_setup.py", line 157, in init_prefix
    LOG.error("Exception: {}".format(str(e)), extra=set_client_ip(request))
Message: "Exception: [Errno 2] No such file or directory: 'data/prefissi.csv'"
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/rao/agency/utils/utils_setup.py", line 144, in init_prefix
    with open(os.path.join(settings.DATA_FILES_PATH, file), encoding='utf-8') as csv_file:
FileNotFoundError: [Errno 2] No such file or directory: 'data/prefissi.csv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/logging/__init__.py", line 994, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 580, in format
    s = self.formatMessage(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 549, in formatMessage
    return self._style.format(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 391, in format
    return self._fmt % record.__dict__
KeyError: 'rao_name'
Call stack:
  File "/usr/local/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/rao/agency/utils/utils.py", line 512, in do_import
    init_prefix(None)
  File "/rao/agency/utils/utils_setup.py", line 158, in init_prefix
    LOG.error('exception_value = %s, value = %s' % (value, type,), extra=set_client_ip(request))
Message: "exception_value = [Errno 2] No such file or directory: 'data/prefissi.csv', value = <class 'type'>"
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/rao/agency/utils/utils_setup.py", line 144, in init_prefix
    with open(os.path.join(settings.DATA_FILES_PATH, file), encoding='utf-8') as csv_file:
FileNotFoundError: [Errno 2] No such file or directory: 'data/prefissi.csv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/logging/__init__.py", line 994, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 580, in format
    s = self.formatMessage(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 549, in formatMessage
    return self._style.format(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 391, in format
    return self._fmt % record.__dict__
KeyError: 'rao_name'
Call stack:
  File "/usr/local/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/rao/agency/utils/utils.py", line 512, in do_import
    init_prefix(None)
  File "/rao/agency/utils/utils_setup.py", line 159, in init_prefix
    LOG.error('tb = %s' % traceback.format_exception(type, value, tb), extra=set_client_ip(request))
Message: 'tb = [\'Traceback (most recent call last):\\n\', \'  File "/rao/agency/utils/utils_setup.py", line 144, in init_prefix\\n    with open(os.path.join(settings.DATA_FILES_PATH, file), encoding=\\\'utf-8\\\') as csv_file:\\n\', "FileNotFoundError: [Errno 2] No such file or directory: \'data/prefissi.csv\'\\n"]'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/rao/agency/utils/utils_setup.py", line 72, in init_county
    with open(os.path.join(settings.DATA_FILES_PATH, file), encoding='utf-8') as csv_file:
FileNotFoundError: [Errno 2] No such file or directory: 'data/province.csv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/logging/__init__.py", line 994, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 580, in format
    s = self.formatMessage(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 549, in formatMessage
    return self._style.format(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 391, in format
    return self._fmt % record.__dict__
KeyError: 'rao_name'
Call stack:
  File "/usr/local/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/rao/agency/utils/utils.py", line 515, in do_import
    init_county(None)
  File "/rao/agency/utils/utils_setup.py", line 84, in init_county
    LOG.error("Exception: {}".format(str(e)), extra=set_client_ip(request))
Message: "Exception: [Errno 2] No such file or directory: 'data/province.csv'"
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/rao/agency/utils/utils_setup.py", line 72, in init_county
    with open(os.path.join(settings.DATA_FILES_PATH, file), encoding='utf-8') as csv_file:
FileNotFoundError: [Errno 2] No such file or directory: 'data/province.csv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/logging/__init__.py", line 994, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 580, in format
    s = self.formatMessage(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 549, in formatMessage
    return self._style.format(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 391, in format
    return self._fmt % record.__dict__
KeyError: 'rao_name'
Call stack:
  File "/usr/local/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/rao/agency/utils/utils.py", line 515, in do_import
    init_county(None)
  File "/rao/agency/utils/utils_setup.py", line 85, in init_county
    LOG.error('exception_value = %s, value = %s' % (value, type,), extra=set_client_ip(request))
Message: "exception_value = [Errno 2] No such file or directory: 'data/province.csv', value = <class 'type'>"
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/rao/agency/utils/utils_setup.py", line 72, in init_county
    with open(os.path.join(settings.DATA_FILES_PATH, file), encoding='utf-8') as csv_file:
FileNotFoundError: [Errno 2] No such file or directory: 'data/province.csv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/logging/__init__.py", line 994, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 580, in format
    s = self.formatMessage(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 549, in formatMessage
    return self._style.format(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 391, in format
    return self._fmt % record.__dict__
KeyError: 'rao_name'
Call stack:
  File "/usr/local/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/rao/agency/utils/utils.py", line 515, in do_import
    init_county(None)
  File "/rao/agency/utils/utils_setup.py", line 86, in init_county
    LOG.error('tb = %s' % traceback.format_exception(type, value, tb), extra=set_client_ip(request))
Message: 'tb = [\'Traceback (most recent call last):\\n\', \'  File "/rao/agency/utils/utils_setup.py", line 72, in init_county\\n    with open(os.path.join(settings.DATA_FILES_PATH, file), encoding=\\\'utf-8\\\') as csv_file:\\n\', "FileNotFoundError: [Errno 2] No such file or directory: \'data/province.csv\'\\n"]'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/rao/agency/utils/utils_setup.py", line 98, in init_municipality
    with open(os.path.join(settings.DATA_FILES_PATH, file), encoding='utf-8') as csv_file:
FileNotFoundError: [Errno 2] No such file or directory: 'data/ANPR_archivio_comuni.csv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/logging/__init__.py", line 994, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 580, in format
    s = self.formatMessage(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 549, in formatMessage
    return self._style.format(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 391, in format
    return self._fmt % record.__dict__
KeyError: 'rao_name'
Call stack:
  File "/usr/local/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/rao/agency/utils/utils.py", line 518, in do_import
    init_municipality(None)
  File "/rao/agency/utils/utils_setup.py", line 129, in init_municipality
    LOG.error("Exception: {}".format(str(e)), extra=set_client_ip(request))
Message: "Exception: [Errno 2] No such file or directory: 'data/ANPR_archivio_comuni.csv'"
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/rao/agency/utils/utils_setup.py", line 98, in init_municipality
    with open(os.path.join(settings.DATA_FILES_PATH, file), encoding='utf-8') as csv_file:
FileNotFoundError: [Errno 2] No such file or directory: 'data/ANPR_archivio_comuni.csv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/logging/__init__.py", line 994, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 580, in format
    s = self.formatMessage(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 549, in formatMessage
    return self._style.format(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 391, in format
    return self._fmt % record.__dict__
KeyError: 'rao_name'
Call stack:
  File "/usr/local/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/rao/agency/utils/utils.py", line 518, in do_import
    init_municipality(None)
  File "/rao/agency/utils/utils_setup.py", line 130, in init_municipality
    LOG.error('exception_value = %s, value = %s' % (value, type,), extra=set_client_ip(request))
Message: "exception_value = [Errno 2] No such file or directory: 'data/ANPR_archivio_comuni.csv', value = <class 'type'>"
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/rao/agency/utils/utils_setup.py", line 98, in init_municipality
    with open(os.path.join(settings.DATA_FILES_PATH, file), encoding='utf-8') as csv_file:
FileNotFoundError: [Errno 2] No such file or directory: 'data/ANPR_archivio_comuni.csv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/logging/__init__.py", line 994, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 580, in format
    s = self.formatMessage(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 549, in formatMessage
    return self._style.format(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 391, in format
    return self._fmt % record.__dict__
KeyError: 'rao_name'
Call stack:
  File "/usr/local/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/rao/agency/utils/utils.py", line 518, in do_import
    init_municipality(None)
  File "/rao/agency/utils/utils_setup.py", line 131, in init_municipality
    LOG.error('tb = %s' % traceback.format_exception(type, value, tb), extra=set_client_ip(request))
Message: 'tb = [\'Traceback (most recent call last):\\n\', \'  File "/rao/agency/utils/utils_setup.py", line 98, in init_municipality\\n    with open(os.path.join(settings.DATA_FILES_PATH, file), encoding=\\\'utf-8\\\') as csv_file:\\n\', "FileNotFoundError: [Errno 2] No such file or directory: \'data/ANPR_archivio_comuni.csv\'\\n"]'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/logging/__init__.py", line 994, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 580, in format
    s = self.formatMessage(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 549, in formatMessage
    return self._style.format(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 391, in format
    return self._fmt % record.__dict__
KeyError: 'rao_name'
Call stack:
  File "/usr/local/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/usr/local/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
  File "/usr/local/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/staticfiles/handlers.py", line 65, in __call__
    return self.application(environ, start_response)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/rao/agency/utils/utils.py", line 538, in check_import
    LOG.info("Setup completato con successo.", extra=set_client_ip(request))
Message: 'Setup completato con successo.'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/logging/__init__.py", line 994, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 580, in format
    s = self.formatMessage(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 549, in formatMessage
    return self._style.format(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 391, in format
    return self._fmt % record.__dict__
KeyError: 'rao_name'
Call stack:
  File "/usr/local/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/usr/local/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
  File "/usr/local/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/staticfiles/handlers.py", line 65, in __call__
    return self.application(environ, start_response)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/rao/agency/decorators.py", line 111, in onCall
    return function(request, *args, **kwargs)
  File "/rao/agency/views.py", line 753, in change_password
    LOG.info("{} - Cambio password avvenuto.".format(username), extra=set_client_ip(request))
```
